name: Generate static data

on:
  schedule:
    - cron: "52 */4 * * *"
  workflow_dispatch:

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install deps
        run: |
          sudo apt -qqq update
          sudo apt -qqq install \
            cpanminus \
            libdatetime-perl \
            libdevel-confess-perl \
            libjson-xs-perl \
            liblwp-protocol-https-perl \
            libtest-exception-perl \
            libtext-csv-xs-perl \
            libxml-libxml-perl \
            libyaml-perl
          cpanm --sudo -qn Data::Mirror Object::Anon

      - name: generate data
        run: |
          mkdir -p data/root data/registrars
          bin/registrars.pl data/registrars
          bin/root.pl data/root

      - name: generate artifact
        run: tar --directory=data -z -c -v -f github-pages .

      - name: configure
        uses: actions/configure-pages@v4

      - name: upload
        uses: actions/upload-pages-artifact@v3

      - name: deploy
        uses: actions/deploy-pages@v4
